### ISSUE TITLE
Add numpy as dependancy when installing package

### ISSUE THREAD

**Issue by T0T4R4** [lkreidberg/batman#31]
The package should automatically install its dependacies, including Numpy.
```Collecting batman-package (from transitleastsquares)
  Downloading https://files.pythonhosted.org/packages/f3/59/a1ca181cafde7c99099da61cd578efc90c4319899a0c31c72241d50b0783/batman-package-2.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-05nyoioa/batman-package/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-05nyoioa/batman-package/```

**Comment by taylorbell57** [comment]
Ditto - just encountered this issue myself when testing the build for my own package that relies on batman

**Comment by jdmoorman** [comment]
I've just opened a PR that uses `pyproject.toml` to specify `numpy` as a build dependency.
