### ISSUE TITLE
batman pip install will crash on a fresh system with no numpy installed.

### ISSUE THREAD

**Issue by 3fon3fonov** [lkreidberg/batman#36]
The problem is that in your setup.py file, line 4 you have:
`import numpy as np`

I often test fresh python instalations on a virtual machine and my Exo-Striker setup.py never works 
straightaway due to:

```
Collecting batman-package
  Downloading batman-package-2.4.6.tar.gz (29 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qgdc17q4/batman-package/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qgdc17q4/batman-package/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i5isigbu
         cwd: /tmp/pip-install-qgdc17q4/batman-package/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-qgdc17q4/batman-package/setup.py", line 4, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

I know.... one could always do a `pip install numpy`, before that, and this is what I am doing,
 but I feel that you can fix your setup.py somehow to avoid this crash. In your 
setup.py you have:

`install_requires = ['numpy'],`

So batman needs numpy to run, but also to run the setup.py, and the only line in the setup.py 
that depends on numpy is 

`include_dirs = [np.get_include()],`

I am not sure what this line does, but if you want to include directories during the installation, perhaps you can use the MANIFEST.in method?

**Comment by 3fon3fonov** [comment]
I just found that this is a duplication of 

https://github.com/lkreidberg/batman/issues/31

**Comment by 3fon3fonov** [comment]
I forgot to close this. I will keep following #31. I hope there is an easy solution to this.
