### ISSUE TITLE
Batman cannot be installed

### ISSUE THREAD

**Issue by martindevora** [lkreidberg/batman#48]
Since a few days I'm not able to install batman (nor any library depending on it). This is what I get:

```
python3.8 -m pip install batman-package
Defaulting to user installation because normal site-packages is not writeable
Collecting batman-package
  Using cached batman-package-2.4.7.tar.gz (394 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.8 /home/fardeau/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp7m7ioa4a
       cwd: /tmp/pip-install-36ubs319/batman-package_7e8b1cd6b3c047f78935953c2067de83
  Complete output (38 lines):
  Checking for OpenMP support...
  Compiler supports OpenMP
  running egg_info
  writing batman_package.egg-info/PKG-INFO
  /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extras_requires'
    warnings.warn(msg)
  Traceback (most recent call last):
    File "/home/fardeau/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/fardeau/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/fardeau/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-qacf88kl/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-qacf88kl/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-qacf88kl/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 79, in <module>
      setup(	name='batman-package',
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-qacf88kl/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 292, in run
      writer(self, ep.name, os.path.join(self.egg_info, ep.name))
    File "/tmp/pip-build-env-qacf88kl/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 628, in write_pkg_info
      metadata.write_pkg_info(cmd.egg_info)
    File "/usr/lib/python3.8/distutils/dist.py", line 1117, in write_pkg_info
      self.write_pkg_file(pkg_info)
    File "/tmp/pip-build-env-qacf88kl/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 172, in write_pkg_file
      license = rfc822_escape(self.get_license())
    File "/usr/lib/python3.8/distutils/util.py", line 475, in rfc822_escape
      lines = header.split('\n')
  AttributeError: 'list' object has no attribute 'split'
  ----------------------------------------
```

**Comment by martindevora** [comment]
This is related to the latest version of setuptools>=56.1. Downgrading to 54.2.0 makes it work.

I think it is related to the license being written as a list instead of as a string in the setup.py file. Can you review it please? If this is not fixed this library will get stuck in the near future.

**Comment by bhilbert4** [comment]
I'm getting the same error. Another, probably unrelated, error seen in the traceback above: the 'extras_requires' entry in setup.py should be 'extras_require'.

**Comment by martindevora** [comment]
As a contingency I've published a fork fixing this in pypi (`vatman-package`) and now it seems that it installs, but the goal would be to get this fixed by the main repo owners as sometimes batman comes as an internal dependency of some other dependencies.

**Comment by vulpicastor** [comment]
I ran into the same problem too, and I concur with @martindevora 's diagnosis. I have taken the liberty to write a one-click-merge pull request to fix this problem.

**Comment by lkreidberg** [comment]
just merged @vulpicastor's PR, many thanks for sorting this out
