### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by Shweta-Dalal** [lkreidberg/batman#53]
Failed to run the test `python -c 'import batman; batman.test()'` after installing using pip on MacOS. 

```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/sdalal/opt/anaconda3/envs/galaxy/lib/python3.9/site-packages/batman/__init__.py", line 6, in <module>
    from .transitmodel import *
  File "/Users/sdalal/opt/anaconda3/envs/galaxy/lib/python3.9/site-packages/batman/transitmodel.py", line 18, in <module>
    from . import _nonlinear_ld
ImportError: numpy.core.multiarray failed to import
```
I tried to install using the source code as well. But the error occurs in the routine `_nonlinear_ld`.

**Comment by matiscke** [comment]
This is probably related to #51 ?

**Comment by lkreidberg** [comment]
CLeaning up some very old issues ... I believe this one was resolved by the fix in issue #51 - please reopen if this is not correct.
