### ISSUE TITLE
Remaining `distutils` incompatibility on Python 3.12 

### ISSUE THREAD

**Issue by mwcraig** [lkreidberg/batman#67]
Although #61 removed `distutils` from `setup.py`, it is still imported in `batman/openmp.py` [here](https://github.com/lkreidberg/batman/blob/master/batman/openmp.py#L2). That makes `import batman` fail on python 3.12 even though it builds fine on python 3.12 with #61. 

It would be great to have a new release on PyPI once it works with python 3.12!

**Comment by ParadoxGuitarist** [comment]
Oh Just for completeness, if you don't upgrade the module with the latest version from github, the test errors: 
```
 podman run -it --rm --pull=never localhost/test python -c "import batman; batman.test()"
Entered start.sh with args: python -c import batman; batman.test()
Running hooks in: /usr/local/bin/start-notebook.d as uid: 1000 gid: 100
Done running hooks in: /usr/local/bin/start-notebook.d
Running hooks in: /usr/local/bin/before-notebook.d as uid: 1000 gid: 100
Sourcing shell script: /usr/local/bin/before-notebook.d/10activate-conda-env.sh
Done running hooks in: /usr/local/bin/before-notebook.d
Executing the command: python -c import batman; batman.test()

Starting tests...

Testing uniform limb darkening model...	
	test passed
Testing linear limb darkening model...	
	test passed
Testing quadratic limb darkening model...	
	test passed
Testing exponential limb darkening model...	
	test passed
Testing logarithmic limb darkening model...	
	test passed
Testing nonlinear limb darkening model...	
	test passed

Testing error tolerance...
	10.0 ppm passed
	1.0 ppm passed
	0.1 ppm passed
	0.01 ppm passed

Testing multithreading...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.12/site-packages/batman/tests.py", line 80, in test
    if detect():
       ^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/batman/openmp.py", line 17, in detect
    compiler = new_compiler()
               ^^^^^^^^^^^^
NameError: name 'new_compiler' is not defined
```
Somewhat related to issue #69. But installing `2.5.1` puts the tests back into the working state (as seen above)

**Comment by lkreidberg** [comment]
thanks and sorry for my very slow response here! I'm mostly an administrator these days :)

I'll get the version sorted out on PyPI.
